### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by righettod** [snyk-labs/awesome-log4shell#79]
Hi,

I don't know if it can be useful for you but I want to share with you my work about log4shell:

* https://github.com/righettod/log4shell-analysis
* https://github.com/righettod/log4shell-payload-grabber

Cheers 😃

**Comment by h4ck3rky13** [comment]
@righettod seems like it would fit well under "Examples & Proofs of Concept"
Feel free to drop it in a PR :D

**Comment by righettod** [comment]
Thank you very much. I proposed the PR #80 😃
